//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bakerySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class CakeType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CakeType()
        {
            this.Cakes = new HashSet<Cake>();
        }
    
        public string ID { get; set; }
        public string TypeName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cake> Cakes { get; set; }
        public virtual CakeType CakeTypes1 { get; set; }
        public virtual CakeType CakeType1 { get; set; }
    }
}
