//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bakerySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public string logID { get; set; }
        public byte[] logInTime { get; set; }
        public string staffID { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
