//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bakerySystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bakerysystemEntities2 : DbContext
    {
        public bakerysystemEntities2()
            : base("name=bakerysystemEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cake> Cakes { get; set; }
        public virtual DbSet<CakeType> CakeTypes { get; set; }
        public virtual DbSet<CustomerScreen> CustomerScreens { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<StatusType> StatusTypes { get; set; }
    }
}
