//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bakerySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public string ID { get; set; }
        public string cakeID { get; set; }
        public string customerID { get; set; }
        public int orderQuantity { get; set; }
        public string addOnWish { get; set; }
        public decimal orderTotal { get; set; }
        public byte[] TimeOfOrder { get; set; }
        public int statusID { get; set; }
    
        public virtual Cake Cake { get; set; }
        public virtual CustomerScreen CustomerScreen { get; set; }
        public virtual StatusType StatusType { get; set; }
    }
}
